import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "@/domains/hotel-booking/components/ui/sonner";
import { connectToDatabase } from "@/domains/hotel-booking/config/database";
// import VerificationStatus from "@/domains/hotel-booking/components/VerificationStatus";

export const metadata: Metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  await connectToDatabase();

  return (
    <html lang="en">
      <body className="antialiased">
        <main>
          {/*<VerificationStatus visible={session && !session?.user?.verified && true} />*/}
          {auth}
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
