// import { CircleCheck, Download, Luggage, Mail, MessageSquareMore, Star } from "lucide-react";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Stripe from "stripe";
import { connectToDatabase } from "@/domains/hotel-booking/config/database";
import { AUTH_CONFIG } from "@/domains/hotel-booking/constants/auth.constants";
import { Booking } from "@/domains/hotel-booking/models";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);

interface PageProps {
  searchParams: Promise<{ session_id?: string }>;
}
export const metadata: Metadata = {
  title: "Payment Success",
  description: "Generated by create next app",
};

const PaymentSuccess = async ({ searchParams }: PageProps) => {
  const { session_id } = await searchParams;

  // Route protection: If no token is provided, kick them back to home
  if (!session_id) {
    redirect(AUTH_CONFIG.ROUTES.HOME);
  }

  await connectToDatabase();

  try {
    const session = await stripe.checkout.sessions.retrieve(session_id);

    if (session.status === "complete" && session.payment_status === "paid") {
      const confirmedBooking = await Booking.findOneAndUpdate(
        { "paymentInfo.stripeSessionId": session_id },
        {
          $set: {
            status: "confirmed",
            "paymentInfo.stripePaymentIntentId": session.payment_intent as string,
            "paymentInfo.paidAt": new Date(),
          },
        },
        { new: true }
      );

      if (!confirmedBooking) {
        return (
          <div className="max-w-md mx-auto my-12 p-6 bg-amber-50 border border-amber-200 rounded-xl text-center">
            <h1 className="text-lg font-bold text-amber-800">Processing Record Allocation</h1>
            <p className="text-gray-600 text-sm mt-1">
              Payment verified, but the local data record allocation is finishing. Refresh briefly.
            </p>
          </div>
        );
      }

      return (
        <div className="max-w-md mx-auto my-16 p-8 bg-white border border-gray-100 rounded-2xl shadow-xs text-center">
          <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4 font-bold text-xl">
            ✓
          </div>
          <h1 className="text-xl font-bold text-gray-900">Booking Confirmed!</h1>
          <p className="text-gray-500 text-sm mt-1">Your stay has been officially secured.</p>
          <div className="mt-6 p-4 bg-gray-50 rounded-xl text-left text-xs space-y-2 font-mono text-gray-600">
            <p>ORDER_ID: {confirmedBooking._id.toString()}</p>
            <p>AMOUNT: ${confirmedBooking.totalAmount.toFixed(2)} USD</p>
          </div>
        </div>
      );
    }
    return (
      <div className="max-w-md mx-auto my-12 p-6 bg-red-50 border border-red-100 rounded-xl text-center">
        <h1 className="font-bold text-red-800">Payment Not Complete</h1>
        <p className="text-gray-600 text-sm mt-1">The status checked out as: {session.payment_status}</p>
      </div>
    );
  } catch (err) {
    console.error("System Sync Failure:", err);
    return (
      <div className="max-w-md mx-auto my-12 p-6 bg-gray-50 border border-gray-200 rounded-xl text-center">
        <h1 className="font-bold text-gray-800">Verification Interrupted</h1>
        <p className="text-gray-500 text-sm mt-1">
          Please refresh the interface to attempt checking verification status again.
        </p>
      </div>
    );
  }

  // return (
  //   <div className="max-w-3xl mx-auto p-6">
  //     {/* Success Message Section */}
  //     <div className="text-center my-12">
  //       <div className="inline-block p-4 bg-green-100 rounded-full mb-6">
  //         <CircleCheck className="fas fa-check-circle text-4xl text-primary" />
  //       </div>
  //       <h1 className="text-3xl font-bold mb-4">Payment Successful!</h1>
  //       <p className="text-zinc-600 mb-8">Your booking has been confirmed. Check your email for details.</p>
  //     </div>
  //     {/* Booking Details Card */}
  //     <div className="bg-white rounded-lg shadow-sm p-6 mb-8">
  //       <div className="flex items-start gap-6 mb-6 pb-6 border-b">
  //         {/*<img
  //           src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1980&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  //           alt="Property"
  //           className="w-32 h-32 rounded-lg object-cover"
  //         />*/}
  //         <div>
  //           <h2 className="text-2xl font-semibold mb-2">Sea View Room</h2>
  //           <div className="flex items-center mb-2">
  //             <Star className="fas fa-star text-sm mr-1" />
  //             <span className="text-sm">4.6 (500+ reviews)</span>
  //           </div>
  //           <p className="text-zinc-600">One room and one living room with a straight sea view....</p>
  //         </div>
  //       </div>
  //       {/* Reservation Details */}
  //       <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
  //         <div>
  //           <h3 className="font-semibold mb-4">Reservation Details</h3>
  //           <div className="space-y-3">
  //             <div className="flex justify-between">
  //               <span className="text-zinc-600 text-sm">Check-in</span>
  //               <span className="text-zinc-500 text-sm">Jan 3, 2025</span>
  //             </div>
  //             <div className="flex justify-between">
  //               <span className="text-zinc-600 text-sm">Check-out</span>
  //               <span className="text-zinc-500 text-sm">Jan 8, 2025</span>
  //             </div>
  //             <div className="flex justify-between">
  //               <span className="text-zinc-600 text-sm">Guests</span>
  //               <span className="text-zinc-500 text-sm">1 guest</span>
  //             </div>
  //           </div>
  //         </div>
  //         <div>
  //           <h3 className="font-semibold mb-4">Payment Summary</h3>
  //           <div className="space-y-3">
  //             <div className="flex justify-between">
  //               <span className="text-zinc-600">Total amount paid</span>
  //               <span className="font-semibold">$364.20</span>
  //             </div>
  //             <div className="flex justify-between text-sm">
  //               <span className="text-zinc-600 text-sm">Booking ID</span>
  //               <span>BOOK123456</span>
  //             </div>
  //           </div>
  //         </div>
  //       </div>
  //     </div>
  //     {/* Next Steps */}
  //     <div className="bg-white rounded-lg shadow-sm p-6 mb-8">
  //       <h3 className="text-xl font-semibold mb-6">Next Steps</h3>
  //       <div className="space-y-6">
  //         <div className="flex gap-4">
  //           <div className="text-primary">
  //             <Mail className="fas fa-envelope text-xl" />
  //           </div>
  //           <div>
  //             <h4 className="font-semibold mb-1">Check your email</h4>
  //             <p className="text-zinc-600">We&apos;ve sent your confirmation and trip details to your email address.</p>
  //           </div>
  //         </div>
  //         <div className="flex gap-4">
  //           <div className="text-primary">
  //             <MessageSquareMore className="fas fa-comment-alt text-xl" />
  //           </div>
  //           <div>
  //             <h4 className="font-semibold mb-1">Message your host</h4>
  //             <p className="text-zinc-600">Introduce yourself and let them know your travel plans.</p>
  //           </div>
  //         </div>
  //         <div className="flex gap-4">
  //           <div className="text-primary">
  //             <Luggage className="fas fa-suitcase text-xl" />
  //           </div>
  //           <div>
  //             <h4 className="font-semibold mb-1">Plan your trip</h4>
  //             <p className="text-zinc-600">Review house rules and check-in instructions in your trip details.</p>
  //           </div>
  //         </div>
  //       </div>
  //     </div>
  //     {/* Action Buttons */}
  //     <div className="flex flex-col sm:flex-row gap-4 justify-center">
  //       <button type="button" className="px-6 py-3 bg-primary text-white rounded-lg hover:brightness-90">
  //         <Download className="fas fa-download mr-2" />
  //         Download Receipt
  //       </button>
  //     </div>
  //     {/* Need Help Section */}
  //     <div className="mt-12 text-center">
  //       <p className="text-zinc-600">Need help with your booking?</p>
  //       <a href={AUTH_CONFIG.ROUTES.HOME} className="text-primary hover:underline">
  //         Visit our Help Center
  //       </a>
  //     </div>
  //   </div>
  // );
};

export default PaymentSuccess;
