import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import AuthHeaderWithProvider from "@/domains/hotel-booking/components/auth/AuthHeaderWithProvider";
import SignUpForm from "@/domains/hotel-booking/components/auth/SignUpForm";
import { auth } from "@/lib/auth";
import { resolveCallbackUrl } from "@/lib/callback-urls";

type SignUpPageProps = {
  searchParams: Promise<{ callbackUrl?: string }>;
};

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const SignUpPage = async ({ searchParams }: SignUpPageProps) => {
  const session = await auth.api.getSession({ headers: await headers() });

  if (session?.user) {
    const resolvedParams = await searchParams;
    const params = new URLSearchParams(resolvedParams as Record<string, string>);
    redirect(resolveCallbackUrl(params));
  }

  // ── Resolve & validate the callback URL ──
  const resolvedParams = await searchParams;
  const params = new URLSearchParams(resolvedParams as Record<string, string>);
  const callbackUrl = resolveCallbackUrl(params);
  return (
    <div>
      <div className=" flex items-center justify-center h-screen">
        <div className="bg-white rounded-xl shadow w-96 p-6 relative">
          <AuthHeaderWithProvider callbackUrl={callbackUrl}>
            <SignUpForm callbackUrl={callbackUrl} />
          </AuthHeaderWithProvider>
        </div>
      </div>
    </div>
  );
};

export default SignUpPage;
