packages:
  - .

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js: set this to true or false
  msw: true
  sharp: true

ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver
