import { differenceInCalendarDays, format, parseISO } from "date-fns";
import type { Metadata } from "next";
import BackToPreviousPage from "@/domains/hotel-booking/components/back-to-previous-page";
import Footer from "@/domains/hotel-booking/components/Footer";
import Navbar from "@/domains/hotel-booking/components/navbar";
import PaymentForm from "@/domains/hotel-booking/components/payment/payment-form";
import { PaymentSummaryCard, YourTrip } from "@/domains/hotel-booking/components/payment/payment-summary-card";
import { getSelectedPropertyDetails } from "@/domains/hotel-booking/db/queries";
import { Suspense } from "react";

type SearchParams = {
  checkin?: string;
  checkout?: string;
  guests?: string;
  [key: string]: string | string[] | undefined;
};

interface Props {
  params: Promise<{
    id: string;
  }>;
  searchParams: Promise<SearchParams>;
}

export const metadata: Metadata = {
  title: "Payment Process",
  description: "Generated by create next app",
};

const PaymentProcess = async ({ params, searchParams }: Props) => {
  const { id } = await params;
  const { checkin, checkout, guests } = await searchParams;

  const property = await getSelectedPropertyDetails(id);

  if (!property) return null;

  const hasBookingDates = !!(checkin && checkout);

  const totalNights = hasBookingDates ? differenceInCalendarDays(parseISO(checkout), parseISO(checkin)) : 0;

  const stayDuration = hasBookingDates
    ? `${format(parseISO(checkin), "MMM d")} - ${format(parseISO(checkout), "d, yyyy")}`
    : "";

  const totalGuests = guests ? `${guests} ${Number(guests) === 1 ? "guest" : "guests"}` : "";

  // const { perNight, cleaningFee, serviceFee } = property.pricing;

  // const accommodationCost = perNight * totalNights;
  // const totalPrice = accommodationCost + cleaningFee + serviceFee;
  return (
    <>
      <Navbar />
      <div className="max-w-7xl mx-auto px-6 py-8">
        <BackToPreviousPage />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          <div>
            <YourTrip stayDuration={stayDuration} totalGuests={totalGuests} />
            <Suspense fallback={<h1 className="text-9xl">Loading...</h1>}>
            <PaymentForm property={JSON.parse(JSON.stringify(property))} totalNights={totalNights} />
            </Suspense>
          </div>
          <div>
            <PaymentSummaryCard property={property} totalNights={totalNights} />
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PaymentProcess;
