import { getSelectedPropertyDetails } from "@/domains/hotel-booking/db/queries";
import { differenceInCalendarDays, format, parseISO } from "date-fns";

import { ChevronLeft } from "lucide-react";
import type { Metadata } from "next";
import Navbar from "@/domains/hotel-booking/components/navbar";
import Link from "next/link";
import Footer from "@/domains/hotel-booking/components/Footer";
import Image from "next/image";
import PaymentForm from "@/domains/hotel-booking/components/payment/payment-form";
import { PaymentSummaryCard, YourTrip } from "@/domains/hotel-booking/components/payment/payment-summary-card";

type SearchParams = {
  checkin?: string;
  checkout?: string;
  guests?: string;
  [key: string]: string | string[] | undefined;
};

interface Props {
  params: Promise<{
    id: string;
  }>;
  searchParams: Promise<SearchParams>;
}

export const metadata: Metadata = {
  title: "Payment Process",
  description: "Generated by create next app",
};

const PaymentProcess = async ({ params,searchParams }: Props) => {
  const { id } = await params;
   const { checkin, checkout, guests } = await searchParams;

   const property = await getSelectedPropertyDetails(id);

   if (!property) return null;

   const hasBookingDates = !!(checkin && checkout);

   const totalNights = hasBookingDates
     ? differenceInCalendarDays(parseISO(checkout), parseISO(checkin))
     : 0;

   const stayDuration = hasBookingDates
     ? `${format(parseISO(checkin), "MMM d")} - ${format(
         parseISO(checkout),
         "d, yyyy"
       )}`
     : "";

   const totalGuests = guests
     ? `${guests} ${Number(guests) === 1 ? "guest" : "guests"}`
     : "";


  return (
    <>
      <Navbar />
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="mb-8">
          <Link
            href="/hotel-booking/details"
            className="inline-flex items-center gap-1 text-zinc-800 hover:underline text-sm font-medium leading-0"
          >
            <ChevronLeft className="size-4" />
              Request to book
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          <div>
            <YourTrip stayDuration={stayDuration} totalGuests={totalGuests} />
            <PaymentForm />

          </div>
          <div>
            <PaymentSummaryCard property={property}
                  totalNights={totalNights} />
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PaymentProcess;
