import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import ManageProperties from "@/domains/hotel-booking/components/create-property/manage-properties";
import Navbar from "@/domains/hotel-booking/components/navbar";
import { getHostProperties } from "@/domains/hotel-booking/db/queries";

export const metadata: Metadata = {
  title: "Manage Hotels",
  description: "Generated by create next app",
};

const ManageList = async () => {
  const properties = await getHostProperties();
  return (
    <>
      <Navbar />

      <div className="max-w-7xl mx-auto px-4 pb-8">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-zinc-900">Manage Properties</h1>
            <p className="text-sm text-zinc-500 mt-1">View, edit, and create listings for your hotel portfolio.</p>
          </div>
          <Button
            type="button"
            className="bg-primary text-white px-4 py-2 rounded-lg hover:brightness-90 transition-colors"
          >
            + Create Hotel
          </Button>
        </div>
        <ManageProperties properties={properties} />
      </div>
    </>
  );
};

export default ManageList;
