/**
 *
 * dynamic metadata
 */
/* export const metadata: Metadata = {
  title: "Maldives Paradise - Hotel",
  description: "Generated by create next app",
}; */

import { auth } from "@/auth";
import Footer from "@/components/Footer";
import Navbar from "@/components/navbar";
import BookingCard from "@/components/property-details/BookingCard";
import { BookingCardForm } from "@/components/property-details/BookingCardForm";
import PropertyAmenities from "@/components/property-details/PropertyAmenities";
import PropertyFeatures from "@/components/property-details/PropertyFeatures";
import PropertyHeader from "@/components/property-details/PropertyHeader";
import PropertyImages from "@/components/property-details/PropertyImages";
import ReviewContainer from "@/components/property-details/ReviewContainer";
import ReviewHeader from "@/components/property-details/ReviewHeader";
import { getSelectedPropertyDetails } from "@/db/queries";
import { PropertyModelDoc } from "@/models/Property";
import { FC } from "react";

// export async function generateMetadata({ params }, parent) {
//   // read route params
//   const movieId = await params.id;

//   // fetch data
//   const movie = await getSelectedMovieDetails(movieId);

//   return {
//     title: `MovieDB - ${movie.title}`,
//     description: movie?.overview.slice(0, 100),
//     openGraph: {
//       images: [
//         {
//           url: `/api/og?id=${movieId}`,
//           width: 1200,
//           height: 600,
//         },
//       ],
//     },
//   };
// }

interface Props {
  params: {
    id: string;
  };
}

const PropertyDetails: FC<Props> = async ({ params: { id } }) => {
  const data: PropertyModelDoc = await getSelectedPropertyDetails(id);
  const session = await auth();

  return (
    <>
      {/* Navbar */}
      <Navbar />
      {/* Property Details Container */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        {/* Property Title and Rating */}
        <PropertyHeader
          name={data?.name}
          rating={data?.avgRating}
          reviews={data?.reviews}
          location={`${data?.location?.street}, ${data?.location?.city}, ${data?.location?.state}`}
        />

        {/* Image Gallery */}
        <PropertyImages images={data?.images} name={data?.name} />
        {/* Property Details */}
        <div className="grid grid-cols-3 gap-8">
          {/* Left Column: Property Description */}
          <div className="col-span-2">
            <PropertyFeatures
              sellerName={data?.seller_info?.name}
              rooms={data.rooms}
              beds={data.beds}
            />
            {/* Amenities */}
            <PropertyAmenities
              description={data?.description}
              amenities={data?.amenities}
            />
          </div>
          {/* Right Column: Booking Card */}
          <div>
            <BookingCard
              pricePerNight={data?.pricePerNight}
              rating={data?.avgRating}
            >
              <BookingCardForm />
            </BookingCard>
          </div>
        </div>
      </div>

      {/* Reviews Section */}
      <div className="max-w-7xl mx-auto px-6 py-12 border-t">
        <div className="grid items-center justify-between mb-8 grid-cols-2">
          <ReviewHeader
            rating={data?.avgRating}
            reviews={data?.reviews?.length}
          />

          <ReviewContainer propertyId={data?._id} />
        </div>
        {/* Show More Button */}
      </div>

      <Footer />
    </>
  );
};

export default PropertyDetails;
