import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { BookingCard } from "@/domains/hotel-booking/components/bookings/booking-card";
import Navbar from "@/domains/hotel-booking/components/navbar";
import { AUTH_CONFIG } from "@/domains/hotel-booking/constants/auth.constants";
import { getUserBookings } from "@/domains/hotel-booking/db/queries";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "My Bookings",
  description: "Generated by create next app",
};

const Bookings = async () => {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (!session?.user?.id) {
    redirect(`${AUTH_CONFIG.ROUTES.HOME}?callbackUrl=/bookings`);
  }

  const bookings = await getUserBookings(session.user.id);
  return (
    <>
      <Navbar />
      {bookings.length === 0 ? (
        <div id="empty-state" className="hidden text-center py-12">
          {/*<img src="./no-bookings-icon.svg" alt="No Bookings" className="mx-auto mb-4 w-32 h-32" />*/}
          <h2 className="text-2xl font-semibold text-gray-800 mb-2">No Bookings Yet</h2>
          <p className="text-zinc-500 text-sm">You haven&apos;t made any bookings. Start exploring amazing stays!</p>
        </div>
      ) : (
        <div className="max-w-4xl mx-auto px-4 py-8">
          <h1 className="text-3xl font-bold mb-6">My Bookings</h1>
          <div className="space-y-4">
            {bookings.map((booking) => (
              <BookingCard key={booking.id} booking={booking} />
            ))}
          </div>
        </div>
      )}
    </>
  );
};

export default Bookings;

/*
import { connectToDatabase } from "@/lib/db";
import Booking from "@/models/Booking";
import { reconcileBookingStatus } from "@/lib/stripe-recovery";

export default async function DashboardPage() {
  await connectToDatabase();
  const rawBookings = await Booking.find({ userId: "user_mock_9921" });

  // Map over the results. Any pending booking checks live data automatically.
  const resolvedBookings = await Promise.all(rawBookings.map(reconcileBookingStatus));

  return (
    <div>
      {resolvedBookings.map((b) => (
        <div key={b._id.toString()}>{b.status}</div>
      ))}
    </div>
  );
}*/
