/**
 *
 * dynamic metadata
 */
/* export const metadata: Metadata = {
  title: "Maldives Paradise - Hotel",
  description: "Generated by create next app",
}; */

// import { auth } from "@/auth";
import Footer from "@/domains/hotel-booking/components/Footer";
import Navbar from "@/domains/hotel-booking/components/navbar";
import BookingCard from "@/domains/hotel-booking/components/property-details/BookingCard";
import { BookingCardForm } from "@/domains/hotel-booking/components/property-details/BookingCardForm";
import PropertyAmenities from "@/domains/hotel-booking/components/property-details/PropertyAmenities";
import PropertyFeatures from "@/domains/hotel-booking/components/property-details/PropertyFeatures";
import PropertyHeader from "@/domains/hotel-booking/components/property-details/PropertyHeader";
import PropertyImages from "@/domains/hotel-booking/components/property-details/PropertyImages";
// import ReviewContainer from "@/domains/hotel-booking/components/property-details/ReviewContainer";
import ReviewHeader from "@/domains/hotel-booking/components/property-details/ReviewHeader";
import { getSelectedPropertyDetails } from "@/domains/hotel-booking/db/queries";

// export async function generateMetadata({ params }, parent) {
//   // read route params
//   const movieId = await params.id;

//   // fetch data
//   const movie = await getSelectedMovieDetails(movieId);

//   return {
//     title: `MovieDB - ${movie.title}`,
//     description: movie?.overview.slice(0, 100),
//     openGraph: {
//       images: [
//         {
//           url: `/api/og?id=${movieId}`,
//           width: 1200,
//           height: 600,
//         },
//       ],
//     },
//   };
// }

interface Props {
  params: Promise<{
    id: string;
  }>;
}
const PropertyDetails = async ({ params }: Props) => {
  const { id } = await params;
  const data = await getSelectedPropertyDetails(id);
  // const session = await auth();

  if (!data) return null;

  return (
    <>
      {/* Navbar */}
      <Navbar />
      {/* Property Details Container */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        {/* Property Title and Rating */}
        <PropertyHeader
          name={data.title}
          rating={data.rating.overall}
          reviews={data.reviews.length}
          location={data.location.address || ""}
        />

        {/* Image Gallery */}
        <PropertyImages images={data?.images} name={data?.title} />
        {/* Property Details */}
        <div className="grid grid-cols-3 gap-8">
          {/* Left Column: Property Description */}
          <div className="col-span-2">
            <PropertyFeatures sellerName={data.host.name} rooms={data.capacity.bedrooms} beds={data.capacity.beds} />
            {/* Amenities */}
            <PropertyAmenities description={data?.description} amenities={data?.amenities} />
          </div>
          {/* Right Column: Booking Card */}
          <div>
            <BookingCard pricePerNight={data?.pricing.perNight} rating={data?.rating.overall}>
              <BookingCardForm />
            </BookingCard>
          </div>
        </div>
      </div>

      {/* Reviews Section */}
      <div className="max-w-7xl mx-auto px-6 py-12 border-t">
        <div className="grid items-center justify-between mb-8 grid-cols-2">
          <ReviewHeader rating={data?.rating.overall} reviews={data?.reviews?.length} />

          {/*<ReviewContainer propertyId={data?._id} />*/}
        </div>
        {/* Show More Button */}
      </div>

      <Footer />
    </>
  );
};

export default PropertyDetails;
