import { auth as nextAuth } from "@/domains/hotel-booking/auth";
import type { Metadata } from "next";
import { Toaster } from "@/domains/hotel-booking/components/ui/sonner";
import VerificationStatus from "@/domains/hotel-booking/components/VerificationStatus";
import { SessionProvider } from "next-auth/react";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // async function changeLocaleAction(locale: Locale) {
  //    'use server';
  //    const store = await cookies();
  //    store.set('locale', locale);
  //  }

  const session = await nextAuth();
  // Providing all messages to the client
  // side is the easiest way to get started
  // revalidatePath("/", "layout");
  return (
    <html lang={locale}>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <NextIntlClientProvider>
            <SessionProvider session={session}>
              <VerificationStatus
                visible={session && !session?.user?.verified}
              />
              {auth}
              {children}
              {/*<LocaleSwitcher changeLocaleAction={changeLocaleAction} />*/}
              <Toaster />
            </SessionProvider>
          </NextIntlClientProvider>
        </main>
      </body>
    </html>
  );
}
