import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Checkout Page",
  description: "Generated by create next app",
};

const CheckoutPage = () => {
  return <h1 className="text-5xl">Checkout Page</h1>;
};

export default CheckoutPage;
