import type { Metadata } from "next";
import "./globals.css";
import connectDB from "@/domains/hotel-booking/config/database";

import { Toaster } from "@/domains/hotel-booking/components/ui/sonner";
// import VerificationStatus from "@/domains/hotel-booking/components/VerificationStatus";

export const metadata: Metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectDB();

  return (
    <html>
      <body className="antialiased">
        <main>
          {/*<VerificationStatus visible={session && !session?.user?.verified && true} />*/}
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
