import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Locale } from "@/i18n/i18n.config";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  auth,
  children,
  params: { locale },
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <main>
            <>{auth}</>
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
