import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { auth as nextAuth } from "@/auth";

import { Locale } from "@/i18n/i18n.config";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import VerificationStatus from "@/components/VerificationStatus";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  auth,
  children,
  params: { locale },
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  const session = await nextAuth();
  console.log(session);
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <NextIntlClientProvider messages={messages}>
            <SessionProvider session={session}>
              <VerificationStatus
                visible={session && !session?.user?.verified ? true : false}
              />
              <>{auth}</>
              {children}
            </SessionProvider>
          </NextIntlClientProvider>
        </main>
      </body>
    </html>
  );
}
