import GoogleLoginAction from "@/components/auth/GoogleLoginAction";
import LoginForm from "@/components/auth/LoginForm";
import LoginNavigation from "@/components/auth/LoginNavigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Modal Container */}
      <div className="bg-white rounded-xl shadow w-96 p-6 relative ">
        {/* Modal Header */}
        <div className="text-center mb-6">
          <h2 className="text-2xl font-bold text-gray-800">
            Log in to Hotel Booking
          </h2>
          <p className="text-gray-600 text-sm mt-2">
            Welcome back! Let&apos;s get you signed in.
          </p>
        </div>
        {/* Social Login */}
        <div className="space-y-4 mb-4">
          {/* Google Login Button */}
          <GoogleLoginAction />

          {/* Divider */}
          <div className="flex items-center my-4">
            <div className="flex-grow border-t border-gray-300" />
            <span className="mx-4 text-gray-500 text-sm">or</span>
            <div className="flex-grow border-t border-gray-300" />
          </div>
          {/* Email Login Form */}
          <LoginForm />
        </div>
        {/* Footer */}
        <LoginNavigation />
      </div>
    </div>
  );
};

export default Login;
