import Navbar from "@/domains/hotel-booking/components/navbar";
import { Button } from "@/domains/hotel-booking/components/ui/button";
import type { Metadata } from "next";
import Image from "next/image";
import {
  FaBed,
  FaDoorOpen,
  FaDumbbell,
  FaPencilAlt,
  FaSave,
  FaSink,
  FaUmbrellaBeach,
  FaWifi,
} from "react-icons/fa";

import {
  FaPen,
  FaPerson,
  FaPersonSwimming,
  FaSquareParking,
} from "react-icons/fa6";

export const metadata: Metadata = {
  title: "Create Hotel",
  description: "Generated by create next app",
};

const Create = () => {
  return (
    <>
      {/* Navbar */}
      <Navbar />

      {/* Property Details Container */}
      <div className="max-w-7xl mx-auto px-6 py-8 relative">
        <Button className="px-4 py-2 bg-primary text-white rounded-lg hover:brightness-90 absolute top-4 right-4">
          <FaSave className="fas fa-save mr-2" />
          Publish
        </Button>
        {/* Property Title and Rating */}
        <div className="mb-6">
          <input
            className="text-zinc-800 font-bold text-3xl outline-primary"
            defaultValue={"Property Name"}
          />
          <Button className="px-4 py-2 bg-primary text-white rounded-lg text-sm ml-4 hover:brightness-90">
            <FaSave className="fas fa-save mr-2" /> Save
          </Button>
          <h1
            className="text-3xl font-bold mb-2 text-zinc-400 edit"
            id="propertyName"
          >
            Property Name
            <FaPencilAlt className="fas fa-pencil-alt text-gray-400 ml-2 cursor-pointer text-sm hover:scale-110 transition-all" />
          </h1>
          <div className="flex items-center text-gray-600">
            <span className="edit text-gray-600">
              Property location{" "}
              <FaPencilAlt className="fas fa-pencil-alt text-gray-400 ml-2 cursor-pointer text-sm hover:scale-110 transition-all" />
            </span>
          </div>
        </div>
        {/* Image Gallery */}
        <div className="grid grid-cols-4 grid-rows-2 gap-4 mb-8 h-[500px]">
          <div className="col-span-2 row-span-2 relative">
            <Image
              src="https://placehold.co/600x400"
              alt="Main Room"
              className="w-full h-full object-cover rounded-lg"
            />
            <input
              type="text"
              placeholder="https://placehold.co/600x400"
              className="w-11/12 p-2 border border-primary rounded-lg mt-2 absolute left-1/2 -translate-x-1/2 bottom-2 bg-white"
            />
          </div>
          <div className="relative">
            <Image
              src="https://placehold.co/600x400"
              alt="Room 1"
              className="w-full h-full object-cover rounded-lg"
            />
            <input
              type="text"
              placeholder="https://placehold.co/600x400"
              className="text-sm w-11/12 p-2 border border-primary rounded-lg mt-2 absolute left-1/2 -translate-x-1/2 bottom-2 bg-white"
            />
          </div>
          <div className="relative">
            <Image
              src="https://placehold.co/600x400"
              alt="Room 2"
              className="w-full h-full object-cover rounded-lg"
            />
            <input
              type="text"
              placeholder="https://placehold.co/600x400"
              className="text-sm w-11/12 p-2 border border-primary rounded-lg mt-2 absolute left-1/2 -translate-x-1/2 bottom-2 bg-white"
            />
          </div>
          <div className="relative">
            <Image
              src="https://placehold.co/600x400"
              alt="Room 3"
              className="w-full h-full object-cover rounded-lg"
            />
            <input
              type="text"
              placeholder="https://placehold.co/600x400"
              className="text-sm w-11/12 p-2 border border-primary rounded-lg mt-2 absolute left-1/2 -translate-x-1/2 bottom-2 bg-white"
            />
          </div>
          <div className="relative">
            <Image
              src="https://placehold.co/600x400"
              alt="Room 4"
              className="w-full h-full object-cover rounded-lg"
            />
            <input
              type="text"
              placeholder="https://placehold.co/600x400"
              className="text-sm w-11/12 p-2 border border-primary rounded-lg mt-2 absolute left-1/2 -translate-x-1/2 bottom-2 bg-white"
            />
          </div>
        </div>
        <div className="mb-4">
          <span className="text-xl font-bold edit">Price in USD</span>
          <span className="text-gray-600 ml-1">per night</span>
        </div>
        <div className="mb-4">
          {/* Stock */}
          <span className="edit">Available X rooms</span>
        </div>
        {/* Property Details */}
        <div className="grid grid-cols-3 gap-8">
          {/* Left Column: Property Description */}
          <div className="col-span-2">
            <div className="border-b pb-6 mb-6">
              <div className="grid grid-cols-1 gap-4 text-gray-600">
                <div className="flex items-center gap-2">
                  <FaPerson className="fas fa-person" />
                  <span className="edit">How many Guest can Stay?</span>
                </div>
                <div className="flex items-center gap-2">
                  <FaDoorOpen className="fas fa-door-open" />
                  <span className="edit">How many Bedrooms ? </span>
                </div>
                <div className="flex items-center gap-2">
                  <FaBed className="fas fa-bed" />
                  <span className="edit">How many beds available ?</span>
                </div>
              </div>
            </div>
            {/* Description */}
            <div className="mb-6">
              <h3 className="text-xl font-semibold mb-4">About this place</h3>
              <p className="text-gray-700 leading-relaxed edit">
                Write a short description about this place
              </p>
              <FaPen />
            </div>
            {/* Amenities */}
            <div>
              <h3 className="text-xl font-semibold mb-4">
                What this place offers
              </h3>
              <div className="grid grid-cols-2 gap-4" id="amenities">
                <div className="flex items-center gap-2 cursor-pointer">
                  <FaUmbrellaBeach className="fa-solid fa-umbrella-beach" />
                  <span>Beach access</span>
                </div>
                <div className="flex items-center gap-2 cursor-pointer">
                  <FaPersonSwimming className="fa-solid fa-person-swimming" />
                  <span>Private pool</span>
                </div>
                <div className="flex items-center gap-2 cursor-pointer">
                  <FaWifi className="fa-solid fa-wifi" />
                  <span>Free Wi-Fi</span>
                </div>
                <div className="flex items-center gap-2 cursor-pointer">
                  <FaSink className="fa-solid fa-sink" />
                  <span>Kitchen</span>
                </div>
                <div className="flex items-center gap-2 cursor-pointer">
                  <FaSquareParking className="fa-solid fa-square-parking" />
                  <span>Free Parking</span>
                </div>
                <div className="flex items-center gap-2 cursor-pointer">
                  <FaDumbbell className="fa-solid fa-dumbbell" />
                  <span>Fitness Center</span>
                </div>
              </div>
            </div>
          </div>
          {/* Right Column: Booking Card */}
        </div>
      </div>
    </>
  );
};

export default Create;
