export const PROPERTY_TYPES = ["Entire home", "Private room", "Shared room", "Unique stay", "Hotel room"] as const;

export const CURRENCIES = ["USD", "EUR", "GBP", "CAD", "AUD", "JPY", "INR"] as const;

// export const AMENITY_OPTIONS = [
//   "WiFi",
//   "Kitchen",
//   "Washer",
//   "Dryer",
//   "Air conditioning",
//   "Heating",
//   "Dedicated workspace",
//   "TV",
//   "Hair dryer",
//   "Iron",
//   "Pool",
//   "Hot tub",
//   "Free parking",
//   "EV charger",
//   "Crib",
//   "Gym",
//   "BBQ grill",
//   "Breakfast",
//   "Indoor fireplace",
//   "Smoking allowed",
//   "Beachfront",
//   "Waterfront",
//   "Ski-in/ski-out",
//   "Smoke alarm",
//   "Carbon monoxide alarm",
// ] as const;

export const AMENITY_OPTIONS = [
  // Essentials & Comfort
  "Wifi",
  "High speed wifi",
  "Pocket wifi",
  "Pocket Wifi",
  "Pocket Wifi included",
  "TV",
  "Smart TV",
  "Bluetooth sound system",
  "Turntable / Record player",
  "Shared media hub",
  "Hangers",
  "Bed linens",
  "Premium linens",
  "Blackout curtains",
  "Books / Reading material",

  // Climate Control
  "Air conditioning",
  "Central AC",
  "Ducted AC system",
  "Heating",
  "Radiant heating",
  "Floor heating",
  "Radiant floor heating",
  "Indoor fireplace",
  "Indoor open hearth",
  "Suspended central fireplace",
  "Suspended central hearth",

  // Kitchen & Dining
  "Kitchen",
  "Chef's kitchen",
  "Shared kitchen",
  "Shared industrial kitchen",
  "Shared luxury kitchen",
  "Kitchenette",
  "Outdoor kitchen",
  "Outdoor kitchen setup",
  "Refrigerator",
  "Wine fridge",
  "Microwave",
  "Microwave grid",
  "Oven",
  "Stove",
  "Gas stove",
  "Gas BBQ",
  "BBQ grill",
  "Toaster",
  "Wine glasses",
  "Wine cellar",
  "Wine cellar access",
  "Wine storage array",

  // Coffee & Drinks
  "Coffee maker",
  "Coffee machine",
  "Coffee bar",
  "Espresso machine",
  "Espresso bar",
  "Nespresso machine",
  "Complimentary espresso",
  "Minibar",
  "Minibar bar row",

  // Bathroom & Wellness
  "Shampoo",
  "Eco toiletries",
  "Hair dryer",
  "Premium bathrobes",
  "Bathtub",
  "Deep soaking tub",
  "Deep soaking cypress tub",
  "Outdoor shower",
  "Outdoor rain shower",
  "Hot tub",
  "Outdoor hot tub",
  "Private hot tub",
  "Wood-fired hot tub",
  "Outdoor timber hot tub",
  "Geothermal outdoor hot tub",
  "Sauna",
  "Shared sauna",
  "Traditional private Hammam",

  // Laundry & Utility
  "Washing machine",
  "Dryer",
  "Iron",
  "Free laundromat access",
  "Laundromat access included",
  "Free industrial laundry row",

  // Parking & Facilities
  "Free parking on premises",
  "Free driveway parking",
  "Garage parking",
  "Double garage",
  "Secure parking",
  "Secure underground parking",
  "Paid parking off premises",
  "EV Charger",
  "Tesla EV Charger",
  "Elevator",

  // Services & Access
  "Lockbox",
  "Smart lock",
  "Personal locking safe",
  "Luggage dropoff allowed",
  "24-hour front desk",
  "24-hour doorman",
  "24-hour concierge service",
  "Concierge desk assistance",
  "Room service",
  "Breakfast included",
  "Breakfast service available",
  "Daily regional meals included",
  "Housekeeping",
  "Housekeeping included",
  "Housekeeping standard",
  "Chef service available",
  "Chef service layout",

  // Business & Work
  "Dedicated workspace",
  "Co-working space",
  "Co-working lounge area",
  "Dedicated library desk",

  // Outdoor & Views
  "Balcony",
  "Porch / Balcony",
  "Patio deck",
  "Outdoor dining area",
  "Outdoor lounge array",
  "Outdoor entertaining deck",
  "Private sun deck",
  "Private stone terrace",
  "Rooftop terrace",
  "Hammock",
  "Sun loungers",
  "Zen garden view",
  "Skylight",
  "Ocean view",
  "Sea view",
  "Caldera ocean view",
  "Panoramic sea view",
  "Beach view",
  "Beachfront",
  "Water view",
  "Lake view",
  "Harbour view",
  "Mountain view",
  "City skyline view",
  "Northern lights view",

  // Activities & Leisure
  "Swimming pool",
  "Private pool",
  "Private plunge pool",
  "Infinity pool",
  "Stock tank pool",
  "Gym",
  "Gym access",
  "Bicycles provided",
  "Kayaks",
  "Kayaks available",
  "Ski-in / Ski-out",
  "Ski storage gear racks",
  "Heated ski gear lockers",
  "Drying cabinet for ski gear",
  "Beach essentials",

  // Shared Spaces / Others
  "Shared bathroom",
  "Shared washrooms",
  "Shared washroom",
  "Shared bathroom layout",
  "Shared lounge",
  "Security system",
  "Mosquito net",
  "Mosquito nets",
  "Solar power",
] as const;
