import { cookies } from "next/headers";
import "./styles.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Footer from "../../components/blog/Footer/Footer";
import Header from "../../components/blog/Header/Header";
import { COLOR_COOKIE_NAME, DARK_TOKENS, LIGHT_TOKENS } from "../../constants";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const savedTheme = await cookies();
  const themValue = savedTheme.get(COLOR_COOKIE_NAME);
  const theme = themValue?.value || "light";
  return (
    <html
      lang="en"
      className={inter.variable}
      data-color-theme={theme}
      style={theme === "light" ? LIGHT_TOKENS : DARK_TOKENS}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header initialTheme={theme} />
        <main>
          {/* <RespectMotionPreference> */}
          {children}
          {/* </RespectMotionPreference> */}
        </main>
        <Footer />
      </body>
    </html>
  );
}
