[
  [
    "/solutions/financial-services",
    [
      {
        parentRow: {
          id: "1",
          url: "/products/enterprise-security",
          targetLinks: "2/3",
          state: "In Progress",
          nestedData: [
            {
              id: "n1a",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "enterprise security solutions",
              status: "ACTIVE",
            },
            {
              id: "n1b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "security infrastructure docs",
              status: "STALE",
              isStale: true,
            },
            {
              id: "n1c",
              title: "API Reference",
              url: "/docs/api-reference-v3",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n1a",
          title: "Financial Services",
          url: "/solutions/financial-services",
          anchor: "enterprise security solutions",
          status: "ACTIVE",
        },
      },
      {
        parentRow: {
          id: "3",
          url: "/resources/technical-whitepaper-v4",
          targetLinks: "3/3",
          state: "Fully Linked",
          nestedData: [
            {
              id: "n3a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "whitepaper security guide",
              status: "ACTIVE",
            },
            {
              id: "n3b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "technical banking paper",
              status: "ACTIVE",
            },
            {
              id: "n3c",
              title: "Future Blog",
              url: "/blog/future-of-automated-links",
              anchor: "automated link research",
              status: "ACTIVE",
            },
          ],
        },
        link: {
          id: "n3b",
          title: "Financial Services",
          url: "/solutions/financial-services",
          anchor: "technical banking paper",
          status: "ACTIVE",
        },
      },
      {
        parentRow: {
          id: "4",
          url: "/blog/future-of-automated-links",
          targetLinks: "0/3",
          state: "Unlinked",
          nestedData: [
            {
              id: "n4a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n4b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n4c",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n4b",
          title: "Financial Services",
          url: "/solutions/financial-services",
          anchor: "",
          status: "UNLINKED",
          isUnlinked: true,
        },
      },
      {
        parentRow: {
          id: "5",
          url: "/docs/api-reference-v3",
          targetLinks: "1/3",
          state: "In Progress",
          nestedData: [
            {
              id: "n5a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "api security reference",
              status: "ACTIVE",
            },
            {
              id: "n5b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n5c",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "api fintech docs",
              status: "STALE",
              isStale: true,
            },
          ],
        },
        link: {
          id: "n5c",
          title: "Financial Services",
          url: "/solutions/financial-services",
          anchor: "api fintech docs",
          status: "STALE",
          isStale: true,
        },
      },
      {
        parentRow: {
          id: "6",
          url: "/about/company-overview",
          targetLinks: "3/3",
          state: "Fully Linked",
          nestedData: [
            {
              id: "n6a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "our security products",
              status: "ACTIVE",
            },
            {
              id: "n6b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "financial solutions overview",
              status: "ACTIVE",
            },
            {
              id: "n6c",
              title: "API Reference",
              url: "/docs/api-reference-v3",
              anchor: "developer resources",
              status: "ACTIVE",
            },
          ],
        },
        link: {
          id: "n6b",
          title: "Financial Services",
          url: "/solutions/financial-services",
          anchor: "financial solutions overview",
          status: "ACTIVE",
        },
      },
    ],
  ],
  [
    "/resources/technical-whitepaper-v4",
    [
      {
        parentRow: {
          id: "1",
          url: "/products/enterprise-security",
          targetLinks: "2/3",
          state: "In Progress",
          nestedData: [
            {
              id: "n1a",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "enterprise security solutions",
              status: "ACTIVE",
            },
            {
              id: "n1b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "security infrastructure docs",
              status: "STALE",
              isStale: true,
            },
            {
              id: "n1c",
              title: "API Reference",
              url: "/docs/api-reference-v3",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n1b",
          title: "Technical Whitepaper",
          url: "/resources/technical-whitepaper-v4",
          anchor: "security infrastructure docs",
          status: "STALE",
          isStale: true,
        },
      },
      {
        parentRow: {
          id: "2",
          url: "/solutions/financial-services",
          targetLinks: "2/3",
          state: "In Progress",
          isExpanded: true,
          nestedData: [
            {
              id: "n2a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "robust fintech security",
              status: "ACTIVE",
            },
            {
              id: "n2b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "banking infrastructure docs",
              status: "STALE",
              isStale: true,
            },
            {
              id: "n2c",
              title: "Future Blog",
              url: "/blog/future-of-automated-links",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n2b",
          title: "Technical Whitepaper",
          url: "/resources/technical-whitepaper-v4",
          anchor: "banking infrastructure docs",
          status: "STALE",
          isStale: true,
        },
      },
      {
        parentRow: {
          id: "4",
          url: "/blog/future-of-automated-links",
          targetLinks: "0/3",
          state: "Unlinked",
          nestedData: [
            {
              id: "n4a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n4b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n4c",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n4c",
          title: "Technical Whitepaper",
          url: "/resources/technical-whitepaper-v4",
          anchor: "",
          status: "UNLINKED",
          isUnlinked: true,
        },
      },
      {
        parentRow: {
          id: "5",
          url: "/docs/api-reference-v3",
          targetLinks: "1/3",
          state: "In Progress",
          nestedData: [
            {
              id: "n5a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "api security reference",
              status: "ACTIVE",
            },
            {
              id: "n5b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n5c",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "api fintech docs",
              status: "STALE",
              isStale: true,
            },
          ],
        },
        link: {
          id: "n5b",
          title: "Technical Whitepaper",
          url: "/resources/technical-whitepaper-v4",
          anchor: "",
          status: "UNLINKED",
          isUnlinked: true,
        },
      },
    ],
  ],
  [
    "/docs/api-reference-v3",
    [
      {
        parentRow: {
          id: "1",
          url: "/products/enterprise-security",
          targetLinks: "2/3",
          state: "In Progress",
          nestedData: [
            {
              id: "n1a",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "enterprise security solutions",
              status: "ACTIVE",
            },
            {
              id: "n1b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "security infrastructure docs",
              status: "STALE",
              isStale: true,
            },
            {
              id: "n1c",
              title: "API Reference",
              url: "/docs/api-reference-v3",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n1c",
          title: "API Reference",
          url: "/docs/api-reference-v3",
          anchor: "",
          status: "UNLINKED",
          isUnlinked: true,
        },
      },
      {
        parentRow: {
          id: "6",
          url: "/about/company-overview",
          targetLinks: "3/3",
          state: "Fully Linked",
          nestedData: [
            {
              id: "n6a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "our security products",
              status: "ACTIVE",
            },
            {
              id: "n6b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "financial solutions overview",
              status: "ACTIVE",
            },
            {
              id: "n6c",
              title: "API Reference",
              url: "/docs/api-reference-v3",
              anchor: "developer resources",
              status: "ACTIVE",
            },
          ],
        },
        link: {
          id: "n6c",
          title: "API Reference",
          url: "/docs/api-reference-v3",
          anchor: "developer resources",
          status: "ACTIVE",
        },
      },
    ],
  ],
  [
    "/products/enterprise-security",
    [
      {
        parentRow: {
          id: "2",
          url: "/solutions/financial-services",
          targetLinks: "2/3",
          state: "In Progress",
          isExpanded: true,
          nestedData: [
            {
              id: "n2a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "robust fintech security",
              status: "ACTIVE",
            },
            {
              id: "n2b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "banking infrastructure docs",
              status: "STALE",
              isStale: true,
            },
            {
              id: "n2c",
              title: "Future Blog",
              url: "/blog/future-of-automated-links",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n2a",
          title: "Enterprise Security",
          url: "/products/enterprise-security",
          anchor: "robust fintech security",
          status: "ACTIVE",
        },
      },
      {
        parentRow: {
          id: "3",
          url: "/resources/technical-whitepaper-v4",
          targetLinks: "3/3",
          state: "Fully Linked",
          nestedData: [
            {
              id: "n3a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "whitepaper security guide",
              status: "ACTIVE",
            },
            {
              id: "n3b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "technical banking paper",
              status: "ACTIVE",
            },
            {
              id: "n3c",
              title: "Future Blog",
              url: "/blog/future-of-automated-links",
              anchor: "automated link research",
              status: "ACTIVE",
            },
          ],
        },
        link: {
          id: "n3a",
          title: "Enterprise Security",
          url: "/products/enterprise-security",
          anchor: "whitepaper security guide",
          status: "ACTIVE",
        },
      },
      {
        parentRow: {
          id: "4",
          url: "/blog/future-of-automated-links",
          targetLinks: "0/3",
          state: "Unlinked",
          nestedData: [
            {
              id: "n4a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n4b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n4c",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n4a",
          title: "Enterprise Security",
          url: "/products/enterprise-security",
          anchor: "",
          status: "UNLINKED",
          isUnlinked: true,
        },
      },
      {
        parentRow: {
          id: "5",
          url: "/docs/api-reference-v3",
          targetLinks: "1/3",
          state: "In Progress",
          nestedData: [
            {
              id: "n5a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "api security reference",
              status: "ACTIVE",
            },
            {
              id: "n5b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
            {
              id: "n5c",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "api fintech docs",
              status: "STALE",
              isStale: true,
            },
          ],
        },
        link: {
          id: "n5a",
          title: "Enterprise Security",
          url: "/products/enterprise-security",
          anchor: "api security reference",
          status: "ACTIVE",
        },
      },
      {
        parentRow: {
          id: "6",
          url: "/about/company-overview",
          targetLinks: "3/3",
          state: "Fully Linked",
          nestedData: [
            {
              id: "n6a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "our security products",
              status: "ACTIVE",
            },
            {
              id: "n6b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "financial solutions overview",
              status: "ACTIVE",
            },
            {
              id: "n6c",
              title: "API Reference",
              url: "/docs/api-reference-v3",
              anchor: "developer resources",
              status: "ACTIVE",
            },
          ],
        },
        link: {
          id: "n6a",
          title: "Enterprise Security",
          url: "/products/enterprise-security",
          anchor: "our security products",
          status: "ACTIVE",
        },
      },
    ],
  ],
  [
    "/blog/future-of-automated-links",
    [
      {
        parentRow: {
          id: "2",
          url: "/solutions/financial-services",
          targetLinks: "2/3",
          state: "In Progress",
          isExpanded: true,
          nestedData: [
            {
              id: "n2a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "robust fintech security",
              status: "ACTIVE",
            },
            {
              id: "n2b",
              title: "Technical Whitepaper",
              url: "/resources/technical-whitepaper-v4",
              anchor: "banking infrastructure docs",
              status: "STALE",
              isStale: true,
            },
            {
              id: "n2c",
              title: "Future Blog",
              url: "/blog/future-of-automated-links",
              anchor: "",
              status: "UNLINKED",
              isUnlinked: true,
            },
          ],
        },
        link: {
          id: "n2c",
          title: "Future Blog",
          url: "/blog/future-of-automated-links",
          anchor: "",
          status: "UNLINKED",
          isUnlinked: true,
        },
      },
      {
        parentRow: {
          id: "3",
          url: "/resources/technical-whitepaper-v4",
          targetLinks: "3/3",
          state: "Fully Linked",
          nestedData: [
            {
              id: "n3a",
              title: "Enterprise Security",
              url: "/products/enterprise-security",
              anchor: "whitepaper security guide",
              status: "ACTIVE",
            },
            {
              id: "n3b",
              title: "Financial Services",
              url: "/solutions/financial-services",
              anchor: "technical banking paper",
              status: "ACTIVE",
            },
            {
              id: "n3c",
              title: "Future Blog",
              url: "/blog/future-of-automated-links",
              anchor: "automated link research",
              status: "ACTIVE",
            },
          ],
        },
        link: {
          id: "n3c",
          title: "Future Blog",
          url: "/blog/future-of-automated-links",
          anchor: "automated link research",
          status: "ACTIVE",
        },
      },
    ],
  ],
];
