import {
  Wifi, Tv, AudioLines, Disc, MonitorPlay, Shirt, BedDouble, SunMoon, BookOpen,
  AirVent, Flame, FlameKindling, ChefHat, Users, Factory, Sparkles, CookingPot,
  UtensilsCrossed, Refrigerator, Grid, Microwave, Heater, Beef, Bean, Wine,
  Coffee, CupSoda, Droplets, Leaf, Wind, Bath, ShowerHead, Waves,
  WashingMachine, SquareParking, Warehouse, ShieldCheck, CircleDollarSign, Zap,
  ArrowUpDown, KeyRound, Lock, Vault, Briefcase, Contact2, ShieldAlert,
  ConciergeBell, Bell, EggFried, Utensils, Brush, Laptop, Building, Layers,
  Footprints, Sun, Flower2, CloudSun, Umbrella, Droplet, Anchor, Mountain,
  Building2, Bike, Ship, MountainSnow, Container, Navigation, Shield,
  type LucideIcon,
  Dumbbell
} from 'lucide-react';

export const AMENITY_MAP: Record<string, LucideIcon> = {
  // Essentials & Comfort
  "Wifi": Wifi,
  "High speed wifi": Wifi,
  "Pocket wifi": Wifi,
  "Pocket Wifi": Wifi,
  "Pocket Wifi included": Wifi,
  "TV": Tv,
  "Smart TV": Tv,
  "Bluetooth sound system": AudioLines,
  "Turntable / Record player": Disc,
  "Shared media hub": MonitorPlay,
  "Hangers": Shirt,
  "Bed linens": BedDouble,
  "Premium linens": BedDouble,
  "Blackout curtains": SunMoon,
  "Books / Reading material": BookOpen,

  // Climate Control
  "Air conditioning": AirVent,
  "Central AC": AirVent,
  "Ducted AC system": AirVent,
  "Heating": Flame,
  "Radiant heating": Flame,
  "Floor heating": Flame,
  "Radiant floor heating": Flame,
  "Indoor fireplace": FlameKindling,
  "Indoor open hearth": FlameKindling,
  "Suspended central fireplace": FlameKindling,
  "Suspended central hearth": FlameKindling,

  // Kitchen & Dining
  "Kitchen": ChefHat,
  "Chef's kitchen": ChefHat,
  "Shared kitchen": Users,
  "Shared industrial kitchen": Factory,
  "Shared luxury kitchen": Sparkles,
  "Kitchenette": CookingPot,
  "Outdoor kitchen": UtensilsCrossed,
  "Outdoor kitchen setup": UtensilsCrossed,
  "Refrigerator": Refrigerator,
  "Wine fridge": Refrigerator,
  "Microwave": Microwave,
  "Microwave grid": Grid,
  "Oven": Microwave,
  "Stove": Heater,
  "Gas stove": Heater,
  "Gas BBQ": Beef,
  "BBQ grill": Beef,
  "Toaster": Bean,
  "Wine glasses": Wine,
  "Wine cellar": Wine,
  "Wine cellar access": Wine,
  "Wine storage array": Wine,

  // Coffee & Drinks
  "Coffee maker": Coffee,
  "Coffee machine": Coffee,
  "Coffee bar": Coffee,
  "Espresso machine": Coffee,
  "Espresso bar": Coffee,
  "Nespresso machine": Coffee,
  "Complimentary espresso": Coffee,
  "Minibar": CupSoda,
  "Minibar bar row": CupSoda,

  // Bathroom & Wellness
  "Shampoo": Droplets,
  "Eco toiletries": Leaf,
  "Hair dryer": Wind,
  "Premium bathrobes": Sparkles,
  "Bathtub": Bath,
  "Deep soaking tub": Bath,
  "Deep soaking cypress tub": Bath,
  "Outdoor shower": ShowerHead,
  "Outdoor rain shower": ShowerHead,
  "Hot tub": Waves,
  "Outdoor hot tub": Waves,
  "Private hot tub": Waves,
  "Wood-fired hot tub": Waves,
  "Outdoor timber hot tub": Waves,
  "Geothermal outdoor hot tub": Waves,
  "Sauna": Flame,
  "Shared sauna": Users,
  "Traditional private Hammam": Sparkles,

  // Laundry & Utility
  "Washing machine": WashingMachine,
  "Dryer": Wind,
  "Iron": Shirt,
  "Free laundromat access": CircleDollarSign,
  "Laundromat access included": CircleDollarSign,
  "Free industrial laundry row": Factory,

  // Parking & Facilities
  "Free parking on premises": SquareParking,
  "Free driveway parking": SquareParking,
  "Garage parking": Warehouse,
  "Double garage": Warehouse,
  "Secure parking": ShieldCheck,
  "Secure underground parking": ShieldCheck,
  "Paid parking off premises": CircleDollarSign,
  "EV Charger": Zap,
  "Tesla EV Charger": Zap,
  "Elevator": ArrowUpDown,

  // Services & Access
  "Lockbox": KeyRound,
  "Smart lock": Lock,
  "Personal locking safe": Vault,
  "Luggage dropoff allowed": Briefcase,
  "24-hour front desk": Contact2,
  "24-hour doorman": ShieldAlert,
  "24-hour concierge service": ConciergeBell,
  "Concierge desk assistance": ConciergeBell,
  "Room service": Bell,
  "Breakfast included": EggFried,
  "Breakfast service available": EggFried,
  "Daily regional meals included": Utensils,
  "Housekeeping": Brush,
  "Housekeeping included": Brush,
  "Housekeeping standard": Brush,
  "Chef service available": ChefHat,
  "Chef service layout": ChefHat,

  // Business & Work
  "Dedicated workspace": Laptop,
  "Co-working space": Briefcase,
  "Co-working lounge area": Briefcase,
  "Dedicated library desk": BookOpen,

  // Outdoor & Views
  "Balcony": Building,
  "Porch / Balcony": Building,
  "Patio deck": Layers,
  "Outdoor dining area": Footprints,
  "Outdoor lounge array": Footprints,
  "Outdoor entertaining deck": Layers,
  "Private sun deck": Sun,
  "Private stone terrace": Grid,
  "Rooftop terrace": Sun,
  "Hammock": Container,
  "Sun loungers": Footprints,
  "Zen garden view": Flower2,
  "Skylight": CloudSun,
  "Ocean view": Waves,
  "Sea view": Waves,
  "Caldera ocean view": Waves,
  "Panoramic sea view": Waves,
  "Beach view": Umbrella,
  "Beachfront": Umbrella,
  "Water view": Droplet,
  "Lake view": Droplet,
  "Harbour view": Anchor,
  "Mountain view": Mountain,
  "City skyline view": Building2,
  "Northern lights view": Sparkles,

  // Activities & Leisure
  "Swimming pool": Waves,
  "Private pool": Waves,
  "Private plunge pool": Waves,
  "Infinity pool": Waves,
  "Stock tank pool": Waves,
  "Gym": Dumbbell,
  "Gym access": Dumbbell,
  "Bicycles provided": Bike,
  "Kayaks": Ship,
  "Kayaks available": Ship,
  "Ski-in / Ski-out": MountainSnow,
  "Ski storage gear racks": Container,
  "Heated ski gear lockers": Lock,
  "Drying cabinet for ski gear": Wind,
  "Beach essentials": Navigation,

  // Shared Spaces / Others
  "Shared bathroom": Users,
  "Shared washrooms": Users,
  "Shared washroom": Users,
  "Shared bathroom layout": Users,
  "Shared lounge": Tv,
  "Security system": Shield,
  "Mosquito net": Shield,
  "Mosquito nets": Shield,
  "Solar power": Sun
};
