import * as Icons from "lucide-react";

const AMENITY_MAP: Record<string, keyof typeof Icons> = {
  "Glass Floor Panels": "Accessibility",
  "Soaking Tub": "Bath",
  "Secure Parking Garage": "Car",
  "Chef Onsite Service": "ChefHat",
  "Breakfast Included": "Coffee",
  "Gym Access": "Dumbbell",
  "Complimentary Wine Cellar": "Martini",
  "Lake View": "Parasol",
  "24/7 Concierge": "ShieldHalf",
  "Washing Machine": "Shirt",
  "Air Conditioning": "SprayCan",
  "Square Chevron Down": "SquareChevronDown",
  "Smart TV Console": "Tv",
  "Full Kitchen": "Utensils",
  "Sky Infinity Pool": "WavesLadder",
  "Free Wi-Fi": "Wifi",

  "Lagoon Access": "Waves",
  "Snorkel Gear": "MasksTheater",
  "Plunge Pool": "Droplet",
  "Private Deck": "Layers",
  "Radiant Heating": "Thermometer",
  "Fireplace": "Flame",
  "Rowboat Access": "Anchor",
  "Patio Setup": "Grid",
  "Bay View View": "Compass",
  "Smart Lock Automation": "KeyRound",
  "High-speed Wi-Fi": "Radio",
  "Mountain View View": "Mountain",
  "Cast Iron Wood Stove": "Heater",
  "Off-Grid Solar": "Sun",
  "Hiking Access Trails": "Footprints",
  "Outdoor Decking": "Columns3",
  "Panoramic Terrace": "View",
  "Balloon View View": "Egg",
  "Traditional Breakfast": "EggFried",
  "Airport Shuttle": "Bus",
  "Cantilever Pool": "Spline",
  "Uninterrupted Sea View": "Eye",
  "Outdoor Built-in BBQ": "Beef",
  "Automated Security System": "ShieldCheck",
  "Private Gym": "Activity",
  "City Skyline Balcony": "Building",
  "Full Kitchen Layout": "CookingPot",
  "Internal Laundry": "WashingMachine",
  "Coffee Maker": "Bean",
  "Manicured Gardens": "Flower2",
  "En-suite Bath": "ShowerHead",
  "Free Wi-Fi Room": "Network",
  "Espresso Bar": "CupSoda",
  "Complimentary High Tea": "Leaf",
  "Heating System": "Gauge",
  "Fiber Optic Wi-Fi": "Cable",
  "Podcast Studio Rig": "Mic",
  "Shared Kitchen Hub": "ForkKnife",
  "Free Laundry Units": "Container",
  "Lockable Storage Units": "Box",
  "Espresso Machine": "GlassWater",
  "Saltwater Pool": "Salad",
  "Outdoor Stargazing Bed": "Telescope",
  "Fire Pit Table": "Table",
  "Tesla EV Charger": "Zap",
  "Monolithic Bath": "BrickWall",
  "Chef Kitchen": "Crown",
  "Hinoki Bath Tub": "Trees",
  "Courtyard Garden": "Sprout",
  "Tatami Mats": "RectangleHorizontal",
  "Traditional Kimonos": "Sparkles",
  "Floor Heating": "TrendingUp",
  "Pocket Wi-Fi": "Smartphone",
  "Rooftop Fire Pit": "CircleDot",
  "Chef Gas Range": "FlameKindling",
  "Smart Workspace": "Laptop",
  "Gigabit Fiber internet": "Globe",
  "Dryer/Washer": "RefreshCw",
  "Caldera Sea Infinity Pool": "Sailboat",
  "Heated Jacuzzi Cavity": "HotTub",
  "Sunset Deck Front": "SunMoon",
  "Luggage Porter Staff": "ConciergeBell",
  "Air Conditioning Unit": "Wind",
  "Aurora Observation Roof": "Moon",
  "Woodfired Sauna Cabin": "House",
  "Fjord Jetty Pier": "Fence",
  "Snowshoe Equipment": "Snowflake",
  "Underfloor Thermal Grid": "Grid2X2",
  "Cast Iron Fireplace": "LogIn",
  "Private Wine Vault": "Wine",
  "Infinity Pool Hill": "TrendingDown",
  "Stone Pizza Hearth": "Disc",
  "Al Fresco Trellis": "Clover",
  "Acreage Olive Trail": "MapPin",
  "Jungle Suspension Net": "Webhook",
  "Natural Spring Pool": "Heart",
  "Private Scooter Entry": "Bike",
  "Organic Breakfast": "Apple",
  "Mosquito Canopy Netting": "Bed",
  "High-speed Wi-Fi Access": "Router",
  "Freestanding Soak Tub": "Calendar",
  "Subzero Pro Vault Kitchen": "Vault",
  "Smart Lighting Mesh": "Lightbulb",
  "Private Gallery Foyer": "FileImage",
  "Hydraulic Drop Down Bed": "ArrowDown",
  "Pocket Wi-Fi Device": "Tablet",
  "Concealed Desk console": "Terminal",
  "Dyson Multi-Filter": "Filter",
  "Washing Machine Combo": "Shuffle",
  "Induction Unit Block": "Square",
  "Private Mooring Pier": "Milestone",
  "Kayaks & SUP Boards": "Ship",
  "Waterfront Sun Decking": "GalleryHorizontal",
  "Outdoor Rain Shower": "CloudRain",
  "WeWeber Gas BBQ Pit": "Bone",
  "Bose Outdoor Soundscape": "Volume2",
  "Internal Plunge Basin": "Circle",
  "Rooftop Giralda View Terrace": "Castle",
  "Handmade Tile Bath": "LayoutGrid",
  "Espresso Bar Console": "Tv2",
  "Full Thermal Radiators": "Columns4",
  "Washing Machine Access": "UserCheck",
  "Suspended Decking Loop": "Repeat",
  "Cedar Outdoor Tub": "Hammer",
  "Wood-fired Stove Grill": "Scissors",
  "Composting Eco Unit": "Recycle",
  "High-speed Wi-Fi Rail": "TrainFront",
  "Rainwater Shower Node": "Cloud",
  "Iron Balcony Front": "UtilityPole",
  "Full Artisan Kitchen": "Brush",
  "Free Wi-Fi Grid": "Grid3X3",
  "Soaking Claw Tub": "Cat",
  "Internal Laundry Array": "ListFilter",
  "Central Heating Loop": "Infinity",
  "Geothermal Floor heat": "HardDrive",
  "Bang Olufsen Audio": "Speaker",
  "Custom Espresso Bar": "WineLabel",
  "Fiber Internet Node": "Share2",
  "Integrated Washer Bed": "Hotel",
  "Ski In Ski Out": "Skateboarding",
  "Stone Hearth Open": "DoorOpen",
  "Finnish Wet Sauna": "Smile",
  "Heated Boot Racks": "FootprintsIcon", // Note: Ensure valid names or aliases
  "Outdoor Jacuzzi Spa": "Eraser",
  "Professional Kitchen Core": "Cpu",
  "Artisanal Mezcal Bar": "GlassWaterIcon",
  "Traditional Comal Stove": "CompassIcon",
  "Cactus Courtyard Garden": "TreePine",
  "Handwoven Hammock Line": "GitCommit",
  "Solar Water Grid": "SunDim",
  "Fiber Internet Mesh": "QrCode",
  "Berber Fire Dining": "UtensilsCrossed",
  "Stargazing Telescope Deck": "Binoculars",
  "Ensuite Copper Shower": "Pipette",
  "Solar Battery Grid": "BatteryCharging",
  "Koala Tracking Deck": "Radar",
  "Outdoor Copper Tub": "Coins",
  "Rainwater Carbon Filter": "Sparkle",
  "WeWeber Charcoal Pit": "FlameIcon",
  "Starlink Internet Node": "Satellite",
  "Neon Ambient Matrix": "Blinds",
  "Monorail View Glass": "Train",
  "Ultra Wide Monitor Loft": "Monitor",
  "Gigabit Router Array": "Server",
  "Capsule Bed System": "BaggageClaim",
  "Glacier Deck View": "IceCream",
  "Heated Ski Gear Box": "Package",
  "Outdoor Hot Basin": "Soup",
  "Full Alpine Kitchen": "Map",
  "Washing Machine Core": "HardHat",
  "Manicured Oak Gardens": "TreePalms",
  "Bespoke Pool Layout": "DraftingCompass",
  "Chef Kitchen Vault": "Key",
  "Outdoor Braai Station": "Eggoptions",
  "Ocean Surf View": "WavesIcon",
  "Geothermal Radiator Loop": "Workflow",
  "Starlink Internet Grid": "SatelliteReceiver",
  "Induction Cook Plate": "TableCells",
  "Compact Wash Module": "Minimize2"
};
type LucideIconComponent = React.ComponentType<Icons.LucideProps>;
interface Props {
  amenities: string[];
  description: string;
}

const PropertyAmenities = ({ description, amenities = [] }:Props) => {
  if (amenities.length == 0) return null;
  return (
    <>
      <div className="mb-6">
        <h3 className="text-xl font-semibold mb-4">About this place</h3>
        <p className="text-gray-700 leading-relaxed">{description}</p>
      </div>
      <div>
        <h3 className="text-xl font-semibold mb-4">What this place offers</h3>
        <div className="grid grid-cols-2 gap-4">
          {amenities.map((amenity, index) => {
            const IconComponent = (Icons[AMENITY_MAP[amenity]] || Icons.SquareChevronDown) as LucideIconComponent;
            return (
              <div key={index} className="flex items-center gap-2">
                <span className="icon"><IconComponent className="w-5 h-5 text-zinc-600 shrink-0" strokeWidth={1.75} /></span>
                <span className="name">{amenity}</span>
              </div>
           )
          } )}
        </div>
      </div>
    </>
  );
};

export default PropertyAmenities;
