export const initialIssues = [
  {
    url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38984",
    repository_url: "https://api.github.com/repos/octocat/Spoon-Knife",
    labels_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38984/labels{/name}",
    comments_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38984/comments",
    events_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38984/events",
    html_url: "https://github.com/octocat/Spoon-Knife/issues/38984",
    id: 3850820508,
    node_id: "I_kwDOABPW4M7lhtuc",
    number: 38984,
    title: "XXX",
    user: {
      login: "sofiaperaza1252-bot",
      id: 237887028,
      node_id: "U_kgDODi3eNA",
      avatar_url: "https://avatars.githubusercontent.com/u/237887028?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/sofiaperaza1252-bot",
      html_url: "https://github.com/sofiaperaza1252-bot",
      followers_url: "https://api.github.com/users/sofiaperaza1252-bot/followers",
      following_url: "https://api.github.com/users/sofiaperaza1252-bot/following{/other_user}",
      gists_url: "https://api.github.com/users/sofiaperaza1252-bot/gists{/gist_id}",
      starred_url: "https://api.github.com/users/sofiaperaza1252-bot/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/sofiaperaza1252-bot/subscriptions",
      organizations_url: "https://api.github.com/users/sofiaperaza1252-bot/orgs",
      repos_url: "https://api.github.com/users/sofiaperaza1252-bot/repos",
      events_url: "https://api.github.com/users/sofiaperaza1252-bot/events{/privacy}",
      received_events_url: "https://api.github.com/users/sofiaperaza1252-bot/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2026-01-24T10:12:32Z",
    updated_at: "2026-01-24T10:12:32Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    sub_issues_summary: {
      total: 0,
      completed: 0,
      percent_completed: 0,
    },
    issue_dependencies_summary: {
      blocked_by: 0,
      total_blocked_by: 0,
      blocking: 0,
      total_blocking: 0,
    },
    body: "> 💕 \n\n _Originally posted by @sofiaperaza1252-bot in [#38945](https://github.com/octocat/Spoon-Knife/pull/38945/changes/BASE..8322de7c09a2f4164ecf37db65e4bf546f84e679#r2702796572)_",
    closed_by: null,
    reactions: {
      url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38984/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38984/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38983",
    repository_url: "https://api.github.com/repos/octocat/Spoon-Knife",
    labels_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38983/labels{/name}",
    comments_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38983/comments",
    events_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38983/events",
    html_url: "https://github.com/octocat/Spoon-Knife/pull/38983",
    id: 3850246532,
    node_id: "PR_kwDOABPW4M6_FDH-",
    number: 38983,
    title: "Update index.html",
    user: {
      login: "kingoxi",
      id: 154007704,
      node_id: "U_kgDOCS34mA",
      avatar_url: "https://avatars.githubusercontent.com/u/154007704?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/kingoxi",
      html_url: "https://github.com/kingoxi",
      followers_url: "https://api.github.com/users/kingoxi/followers",
      following_url: "https://api.github.com/users/kingoxi/following{/other_user}",
      gists_url: "https://api.github.com/users/kingoxi/gists{/gist_id}",
      starred_url: "https://api.github.com/users/kingoxi/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/kingoxi/subscriptions",
      organizations_url: "https://api.github.com/users/kingoxi/orgs",
      repos_url: "https://api.github.com/users/kingoxi/repos",
      events_url: "https://api.github.com/users/kingoxi/events{/privacy}",
      received_events_url: "https://api.github.com/users/kingoxi/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2026-01-24T05:15:28Z",
    updated_at: "2026-01-25T14:22:52Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/octocat/Spoon-Knife/pulls/38983",
      html_url: "https://github.com/octocat/Spoon-Knife/pull/38983",
      diff_url: "https://github.com/octocat/Spoon-Knife/pull/38983.diff",
      patch_url: "https://github.com/octocat/Spoon-Knife/pull/38983.patch",
      merged_at: null,
    },
    body: null,
    closed_by: null,
    reactions: {
      url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38983/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38983/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38980",
    repository_url: "https://api.github.com/repos/octocat/Spoon-Knife",
    labels_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38980/labels{/name}",
    comments_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38980/comments",
    events_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38980/events",
    html_url: "https://github.com/octocat/Spoon-Knife/pull/38980",
    id: 3848199557,
    node_id: "PR_kwDOABPW4M6--KeV",
    number: 38980,
    title: "Update README.md",
    user: {
      login: "mayinx",
      id: 126368,
      node_id: "MDQ6VXNlcjEyNjM2OA==",
      avatar_url: "https://avatars.githubusercontent.com/u/126368?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/mayinx",
      html_url: "https://github.com/mayinx",
      followers_url: "https://api.github.com/users/mayinx/followers",
      following_url: "https://api.github.com/users/mayinx/following{/other_user}",
      gists_url: "https://api.github.com/users/mayinx/gists{/gist_id}",
      starred_url: "https://api.github.com/users/mayinx/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/mayinx/subscriptions",
      organizations_url: "https://api.github.com/users/mayinx/orgs",
      repos_url: "https://api.github.com/users/mayinx/repos",
      events_url: "https://api.github.com/users/mayinx/events{/privacy}",
      received_events_url: "https://api.github.com/users/mayinx/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2026-01-23T16:28:56Z",
    updated_at: "2026-01-24T10:04:03Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/octocat/Spoon-Knife/pulls/38980",
      html_url: "https://github.com/octocat/Spoon-Knife/pull/38980",
      diff_url: "https://github.com/octocat/Spoon-Knife/pull/38980.diff",
      patch_url: "https://github.com/octocat/Spoon-Knife/pull/38980.patch",
      merged_at: null,
    },
    body: "This is a crucial PR to add crucial info to the README.md!",
    closed_by: null,
    reactions: {
      url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38980/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/octocat/Spoon-Knife/issues/38980/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
];
