import type { Metadata } from "next";
import SignIn from "@/domains/hotel-booking/components/auth/SignIn";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="bg-white rounded-xl shadow w-96 p-6 relative ">
        <SignIn />
      </div>
    </div>
  );
};

export default Login;
