import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import SignInHeaderWithGoogleProvider from "@/domains/hotel-booking/components/auth/SignIn";
import SignInForm from "@/domains/hotel-booking/components/auth/SignInForm";
import { auth } from "@/lib/auth";
import { resolveCallbackUrl } from "@/lib/callback-urls";

type SignInPageProps = {
  searchParams: Promise<{ callbackUrl?: string }>;
};

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const SignInPage = async ({ searchParams }: SignInPageProps) => {
  const session = await auth.api.getSession({ headers: await headers() });

  if (session?.user) {
    const resolvedParams = await searchParams;
    const params = new URLSearchParams(resolvedParams as Record<string, string>);
    redirect(resolveCallbackUrl(params));
  }

  // ── Resolve & validate the callback URL ──
  const resolvedParams = await searchParams;
  const params = new URLSearchParams(resolvedParams as Record<string, string>);
  const callbackUrl = resolveCallbackUrl(params);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="bg-white rounded-xl shadow w-96 p-6 relative ">
        <SignInHeaderWithGoogleProvider />
        <SignInForm callbackUrl={callbackUrl} />
      </div>
    </div>
  );
};

export default SignInPage;
